# Generated by Django 2.2 on 2020-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
