# Generated by Django 2.2 on 2020-05-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
