# Generated by Django 2.2 on 2020-05-30 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20200531_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='name',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile'),
        ),
    ]
