# Generated by Django 2.2 on 2020-05-30 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200531_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='messages',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Messages'),
        ),
    ]
