# Generated by Django 2.2 on 2020-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200531_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='Isent',
            field=models.BooleanField(default=False),
        ),
    ]
