# Generated by Django 2.2 on 2020-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_friends_isent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='Isent',
            field=models.IntegerField(default=1),
        ),
    ]
