# Generated by Django 2.2 on 2020-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200601_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friends',
            name='Isent',
            field=models.BooleanField(default=False),
        ),
    ]
